### ISSUE TITLE
F# .cson File

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/atom-fsharp#70]
# ToDo
- [ ] Update AAAPackageDev to handle foldingStartMarker, foldingEndMarker?
- [ ] Revert f#.cson to https://fsharp-tmbundle.googlecode.com/files/FSharp.tmbundle.0.5.zip
- [ ] Edit using AAAPackageDev because of its much clearer regular expression display.
- [ ] Add (?x) to all regular expressions to enable free-spacing mode
- [ ] Re-incorporate (but fix) changes from https://github.com/hoest/sublimetext-fsharp
- [ ] Re-incorporate (but fix) changes from https://github.com/fsharp/sublime-fsharp-package

# Add folding support?
https://atom.io/docs/v0.194.0/using-atom-folding
Do we want to add this functionality? Then modify:
```
foldingStartMarker: ''
foldingStopMarker: ''
```
# Useful Tools
## Sublime Text 3 AAAPackageDev
https://github.com/SublimeText/AAAPackageDev

AAAPackageDev is a Sublime Text 2 and 3 plugin that helps create and edit syntax definitions, snippets, completions files, build systems and other Sublime Text extensions.

## GitHub Lightshow for checking Github Syntax Highlighting
https://github-lightshow.herokuapp.com/

## `.cson` / .`.json` conversion
https://github.com/bevry/cson can convert between `.cson` and `.json`

## tmTheme Editor
https://tmtheme-editor.herokuapp.com/#!/editor/theme/Atom%20Dark
https://github.com/aziz/tmTheme-Editor

# References
## Atom
https://atom.io/docs/v0.209.0/hacking-atom-converting-from-textmate
https://atom.io/docs/v0.186.0/creating-a-package#language-grammars

Atom doesn't have much documentation on writing syntax grammars. So use the following (mostly compatible resources instead):

## TextMate 
http://manual.macromates.com/en/language_grammars
http://manual.macromates.com/en/scope_selectors.html
http://blog.macromates.com/2005/introduction-to-scopes/
https://developmentality.wordpress.com/2011/02/08/textmate-introduction-to-language-grammars/

## Sublime Text 3
http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html
http://docs.sublimetext.info/en/latest/reference/syntaxdefs.html

## Atom Syntax Tools
https://github.com/klorenz/atom-syntax-tools

## Oniguruma regular expression library
https://manual.macromates.com/en/regular_expressions
http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt
https://github.com/atom/node-oniguruma

## CSON
https://github.com/bevry/cson

## JSON
http://json.org/

## YAML
http://www.yaml.org/spec/1.2/spec.html

**Comment by Krzysztof-Cieslak** [comment]
I've updated grammar definition file - I've found in the internet much easier too understand definition file, converted it to JSON and added some changes for better highlighting. Please review file and check if discussed in issue changes are still necessary.
